CONFIG:
  PREFIX: '?'
  MAINTAINERS:
    - 576322791129743361 # Поменяйте на свой ID
  LOG_CHANNEL_ID: 169258459177549824 # Поменяйте на ID канала для основного лога
  XP_LOG_CHANNEL_ID: 276430581468889089 # Поменяйте на ID канала для лога, связанного с опытом и уровнями
  STATUS: "with XP orbs"
  SHOW_NO_PERMS_MESSAGES: true # отобржвть сообщения о недостатке прав или нет (true / false)
  GIPHY_API_KEY: abcdefg12345 # ключ API GIPHY
  GENIUS_API_KEY: asdajks12jkh4kjh # ключ GENIUS API

WHITELIST:
  - 612406451109101599 # The Library
  - 612985606577979421 # The Library: Forbidden Section
  - 626161393103798272 # Defracted Discord

INITIAL_COGS: # Модули, загружаемые при запуске бота
  - 'Twig.Cogs.Events'
  - 'Twig.Cogs.Admin'
  - 'Twig.Cogs.BotOwner'
  - 'Twig.Cogs.EventsLevels'
  - 'Twig.Cogs.TwigExclusives'
  - 'Twig.Cogs.Utils'
  - 'Twig.Cogs.ErrorHandler'
  - 'Twig.Cogs.LevelsCommands'
  - 'Twig.Cogs.HelpCustomization'
  - 'Twig.Cogs.Shop'
  - 'Twig.Cogs.Welcomer'
  - 'Twig.Cogs.Fun'

IGNORED_CHANNELS: # Названия каналов, которые будут игнорироваться при получении опыта
  - 'commands'
  - 'keepers-commands'
  - 'play-this'